apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello
  labels:
    app: spring-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      # 노드 그룹 'default-node-group'에만 스케줄하도록 affinity 설정
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/nodegroup
                    operator: In
                    values:
                      - default-node-group
      containers:
        - name: spring-hello
          image: 136650373268.dkr.ecr.ap-northeast-2.amazonaws.com/spring-hello-gradle:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

